name: Deploy Firebase
"on":
    push:
        branches:
            - master
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
            - name: Build client
              run: npm ci && npm run build
              working-directory: packages/client
            - name: Build words
              run: npm ci && npm run build
              working-directory: packages/words
            - name: Build functions
              run: npm ci && npm run build
              working-directory: packages/functions
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@v2.0.0
              with:
                  args: deploy --only hosting,functions
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
