name: Deploy Cloudflare
"on":
    push:
        branches:
            - master
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm ci
              working-directory: packages/worker
            - run: npm i --no-save @cloudflare/wrangler # already installed locally as well due to Apple M1 workaround
              working-directory: packages/worker
            - run: npm run publish
              working-directory: packages/worker
              env:
                  CF_API_TOKEN: "${{ secrets.CF_API_TOKEN }}"
