name: Deploy Firebase
"on":
    push:
        branches:
            - master
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm ci
              working-directory: packages/client
            - run: npm run build
              working-directory: packages/client
            - run: npm ci
              working-directory: packages/functions
            - run: npm run build
              working-directory: packages/functions
            - name: GitHub Action for Firebase
              uses: w9jds/firebase-action@v2.0.0
              with:
                  args: deploy --only hosting,functions
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
